#!/usr/bin/zsh

while true; do
  date=$(date +'%Y-%m-%d %X')
  volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{if($3 == "[MUTED]") print "MUTE"; else print $2}')
  echo "${date} VOL: ${volume}"
  sleep 1
done
