if has('win32')
    if !has('nvim')
        let s:vimplugpath=expand("$HOME/vimfiles/autoload/plug.vim")
        let s:vimplugdist=expand("$HOME/vimfiles/plugged")
    endif
else
    if has('nvim')
        let s:vimplugpath="$HOME/.local/share/nvim/site/autoload/plug.vim"
        let s:vimplugdist="$HOME/.config/nvim/plugged"
    else
        let s:vimplugpath="$HOME/.vim/autoload/plug.vim"
        let s:vimplugdist="$HOME/.vim/plugged"
    endif
endif
let s:vimplugurl="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

if !filereadable(expand(s:vimplugpath))
    execute "!curl -fLo " . s:vimplugpath . " --create-dirs " . s:vimplugurl
endif

call plug#begin(expand(s:vimplugdist))
" Filetype
Plug 'rust-lang/rust.vim', { 'for': 'rust' }
Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }
Plug 'LnL7/vim-nix', { 'for': 'nix' }
Plug 'lervag/vimtex', { 'for': 'tex' }

" Frontend
Plug 'junegunn/fzf' | Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'wakatime/vim-wakatime'

" Complete/Lint
Plug 'w0rp/ale', { 'for': ['sh', 'c', 'cpp', 'ruby', 'python', 'nix'] }
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
if ! has('nvim')
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/async.vim'
  Plug 'prabirshrestha/vim-lsp'
  Plug 'prabirshrestha/asyncomplete-buffer.vim'
  Plug 'prabirshrestha/asyncomplete-file.vim'
  Plug 'prabirshrestha/asyncomplete-lsp.vim'
  Plug 'yami-beta/asyncomplete-omni.vim'
endif

Plug 'morhetz/gruvbox'
Plug 'cohama/lexima.vim'
if ! has('win32')
  Plug 'mattn/webapi-vim', { 'for': ['html', 'eruby'] } |
              \ Plug 'mattn/emmet-vim'
endif
Plug 'majutsushi/tagbar'
Plug 'tpope/vim-obsession'
Plug 'scrooloose/nerdcommenter'
call plug#end()

if !has('win32')
    colorscheme gruvbox
    set background=light
endif

if !has('nvim')
    set termguicolors

    " Enable escape sequence on :terminal
    tmap <expr> <Esc>]b SendToTerm("\<Esc>]b")
    func SendToTerm(what)
      call term_sendkeys('', a:what)
      return ''
    endfunc
endif

set number
set cursorline

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent

if has('win32')
    set encoding=cp932
else
    set encoding=utf-8
endif

"set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
set fileformats=unix,dos,mac

nnoremap <space> <nop>
let mapleader="\<Space>"

inoremap fd <ESC>
tnoremap <ESC> <C-\><C-n>
tnoremap fd <C-\><C-n>

nnoremap <leader>wh <C-w>h
nnoremap <leader>wj <C-w>j
nnoremap <leader>wk <C-w>k
nnoremap <leader>wl <C-w>l
nnoremap <leader>wH <C-w>H
nnoremap <leader>wJ <C-w>J
nnoremap <leader>wK <C-w>K
nnoremap <leader>wL <C-w>L

nnoremap <leader>wv :vs<CR>
nnoremap <leader>ws :sp<CR>

nnoremap <leader>bq :quit<CR>
nnoremap <leader>bQ :quit!<CR>
nnoremap <leader>bw :write<CR>
nnoremap <leader>bs :wq<CR>

nnoremap <leader>be G
nnoremap <leader>bh gg

nnoremap <F2> :e $MYVIMRC<CR>
nnoremap <F3> :so $MYVIMRC<CR>
nnoremap <F6> :e $MYGVIMRC<CR>
nnoremap <F7> :so $MYGVIMRC<CR>

augroup augrp
    au!

    " Ruby indent
    au filetype ruby set tabstop=2
    au filetype ruby set shiftwidth=2
    au filetype ruby set softtabstop=2
    au filetype eruby set tabstop=2
    au filetype eruby set shiftwidth=2
    au filetype eruby set softtabstop=2

    " Cpp indent
    au filetype cpp set tabstop=2
    au filetype cpp set shiftwidth=2
    au filetype cpp set softtabstop=2
    au filetype c set tabstop=2
    au filetype c set shiftwidth=2
    au filetype c set softtabstop=2

    " NASM
    au BufRead,BufNewFile *.nasm set filetype=nasm
augroup END

function! GetBufferList()
    redir =>buflist
    silent! ls!
    redir END
    return buflist
endfunction

function! ToggleList(bufname, pfx)
    let buflist = GetBufferList()
    for bufnum in map(filter(split(buflist, '\n'), 'v:val =~ "'.a:bufname.'"'), 'str2nr(matchstr(v:val, "\\d\\+"))')
        if bufwinnr(bufnum) != -1
            exec(a:pfx.'close')
            return
        endif
    endfor
    if a:pfx == 'l' && len(getloclist(0)) == 0
        echohl ErrorMsg
        echo "Location List is Empty."
        return
    endif
    let winnr = winnr()
    exec(a:pfx.'open')
    if winnr() != winnr
        wincmd p
    endif
endfunction

command -bang -nargs=? QFix call QFixToggle(<bang>0)
function! QFixToggle(forced)
    if exists("g:qfix_win") && a:forced == 0
        cclose
        unlet g:qfix_win
    else
        copen 10
        let g:qfix_win = bufnr("$")
    endif
endfunction

nmap <silent> Q :QFix<CR>

command! -bang -nargs=* Rg
            \ call fzf#vim#grep(
            \   'rg --ignore-case --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
            \   <bang>0 ? fzf#vim#with_preview('up:60%')
            \           : fzf#vim#with_preview('right:50%:hidden', '?'),
            \   <bang>0)

command! -bang -nargs=* Rgc
            \ call fzf#vim#grep(
            \   'rg --case-sensitive --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
            \   <bang>0 ? fzf#vim#with_preview('up:60%')
            \           : fzf#vim#with_preview('right:50%:hidden', '?'),
            \   <bang>0)

set hidden

let g:ale_linters={
            \   'ruby': ['rubocop'],
            \   'rust': []
            \}
let g:ale_set_quickfix=1
let g:ale_nasm_nasm_options = '-felf64'

let g:UltiSnipsJumpForwardTrigger	= "<c-j>"
let g:UltiSnipsJumpBackwardTrigger	= "<c-k>"
let g:UltiSnipsRemoveSelectModeMappings = 0

if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '-background-index']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif

"if ! has('win32')
"  let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('$HOME/.vim/snippets_custom.json')), "\n"))
"  
"endif
