#! /bin/sh

sxhkd -c $HOME/.config/sxhkd/bspwm &
#polybar bar&
#compton&
feh --bg-scale $HOME/Wallpapers/wall

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a :9menu manage=off border=off

bspc config border_width 4
bspc config window_gap 0
bspc config top_padding 30
bspc config right_padding 30
bspc config bottom_padding 57
bspc config left_padding 30

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color "#606060"
bspc config focused_border_color "#6060A0"

bspc config click_to_focus button1
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
